theme: jekyll-theme-merlot
title: Welcome to Indigo Pixels!
description: Download the latest version of our game from Github!
show_downloads: "true"
github:
  zip_url: https://github.com/KirbyZX/IndigoPixel/zip/master/heartbroken/builds/v0.0.2
