theme: jekyll-theme-merlot
title: Welcome to Indigo Pixels!
description: What a bunch of legends.
show_downloads: "true"
github:
  zip_url: https://github.com/KirbyZX/IndigoPixel/latest-version
  tar_url: https://github.com/KirbyZX/IndigoPixel/tarball/latest-version
