theme: jekyll-theme-merlot
title: Welcome to Indigo Pixels!
description: Work still in progress.
show_downloads: "true"
github:
  zip_url: https://github.com/KirbyZX/IndigoPixel/zipball/heartbroken/builds/v0.0.2
  tar_url: 
