theme: jekyll-theme-merlot
title: Welcome to Indigo Pixels!
description: Work still in progress.
show_downloads: "true"
github:
  zip_url: https://github.com/KirbyZX/IndigoPixel/zipball/latest-version
  tar_url: 
