theme: jekyll-theme-merlot
title: Welcome to Indigo Pixels!
description: We are a bit legendary.
show_downloads: "true"
github:
  zip_url: https://github.com/KirbyZX/IndigoPixel/heartbroken/builds/v0.0.2/zipball/master
